server {
    listen 80;
    server_name __PLACEHOLDER_SUBDOMAIN__;

    location / {
        root /var/www/eli-pilot-control;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name __PLACEHOLDER_SUBDOMAIN__;

    ssl_certificate /etc/ssl/certs/placeholder.crt;
    ssl_certificate_key /etc/ssl/private/placeholder.key;

    location / {
        root /var/www/eli-pilot-control;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
