"""Recommendations API routes."""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List

from app.core.database import get_db
from app.models import Recommendation, Project

router = APIRouter()


@router.get("/", response_model=List[dict])
async def list_recommendations(
    project_id: int | None = None,
    status: str | None = None,
    category: str | None = None,
    skip: int = 0,
    limit: int = 100,
    db: AsyncSession = Depends(get_db),
):
    """List recommendations."""
    query = select(Recommendation)
    
    if project_id:
        query = query.where(Recommendation.project_id == project_id)
    if status:
        query = query.where(Recommendation.status == status)
    if category:
        query = query.where(Recommendation.category == category)
    
    result = await db.execute(query.order_by(Recommendation.priority_score.desc()).offset(skip).limit(limit))
    recommendations = result.scalars().all()
    
    return recommendations


@router.get("/priority")
async def get_priority_recommendations(
    project_id: int,
    limit: int = 10,
    db: AsyncSession = Depends(get_db),
):
    """Get top priority recommendations."""
    result = await db.execute(
        select(Recommendation)
        .where(Recommendation.project_id == project_id)
        .order_by(Recommendation.priority_score.desc())
        .limit(limit)
    )
    recommendations = result.scalars().all()
    
    return {
        "project_id": project_id,
        "top_recommendations": recommendations,
        "count": len(recommendations)
    }


@router.post("/{rec_id}/complete")
async def complete_recommendation(
    rec_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Mark a recommendation as completed."""
    result = await db.execute(select(Recommendation).where(Recommendation.id == rec_id))
    rec = result.scalar_one_or_none()
    
    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")
    
    rec.status = "completed"
    await db.commit()
    await db.refresh(rec)
    
    return rec


@router.post("/generate/{project_id}")
async def generate_recommendations(
    project_id: int,
    db: AsyncSession = Depends(get_db),
):
    """Generate recommendations from audit data."""
    # Verify project exists
    result = await db.execute(select(Project).where(Project.id == project_id))
    project = result.scalar_one_or_none()
    
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # TODO: Trigger SEO Auditor Agent to generate recommendations
    return {
        "project_id": project_id,
        "status": "generation_queued",
        "message": "Recommendations will be generated by SEO Auditor Agent"
    }
