"""add media writer crawler report models

Revision ID: 1278d851
Revises: 
Create Date: 2026-01-31

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1278d851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Batch jobs tables
    op.create_table('batch_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uuid', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('batch_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('cancelled_items', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_jobs_batch_uuid'), 'batch_jobs', ['batch_uuid'], unique=True)
    op.create_index(op.f('ix_batch_jobs_id'), 'batch_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_organization_id'), 'batch_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_project_id'), 'batch_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_user_id'), 'batch_jobs', ['user_id'], unique=False)
    
    op.create_table('batch_job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_job_id', sa.Integer(), nullable=False),
    sa.Column('media_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_job_id'], ['batch_jobs.id'], ),
    sa.ForeignKeyConstraint(['media_job_id'], ['media_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_job_items_batch_job_id'), 'batch_job_items', ['batch_job_id'], unique=False)
    op.create_index(op.f('ix_batch_job_items_id'), 'batch_job_items', ['id'], unique=False)
    
    # Webhook tables
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_uuid', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=1000), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=True),
    sa.Column('signing_secret', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_webhooks_organization_id'), 'webhooks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhooks_webhook_uuid'), 'webhooks', ['webhook_uuid'], unique=True)
    
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body_preview', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_organization_id'), 'webhook_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    
    # Report tables
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_uuid', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('data_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_report_uuid'), 'reports', ['report_uuid'], unique=True)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    
    op.create_table('report_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('storage_file_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['storage_file_id'], ['storage_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_id'), 'report_exports', ['id'], unique=False)
    op.create_index(op.f('ix_report_exports_report_id'), 'report_exports', ['report_id'], unique=False)
    
    # Writer tables
    op.create_table('writer_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_uuid', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=1000), nullable=False),
    sa.Column('target_keyword', sa.String(length=500), nullable=True),
    sa.Column('search_intent', sa.String(length=200), nullable=True),
    sa.Column('tone', sa.String(length=200), nullable=True),
    sa.Column('brand_voice', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writer_jobs_id'), 'writer_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_writer_jobs_job_uuid'), 'writer_jobs', ['job_uuid'], unique=True)
    op.create_index(op.f('ix_writer_jobs_organization_id'), 'writer_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_writer_jobs_project_id'), 'writer_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_writer_jobs_user_id'), 'writer_jobs', ['user_id'], unique=False)
    
    op.create_table('writer_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('h1', sa.String(length=500), nullable=True),
    sa.Column('meta_title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('body_content', sa.Text(), nullable=False),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('entities_detected', sa.JSON(), nullable=True),
    sa.Column('internal_links_suggested', sa.JSON(), nullable=True),
    sa.Column('faq_ideas', sa.JSON(), nullable=True),
    sa.Column('schema_suggestion', sa.JSON(), nullable=True),
    sa.Column('repurposing_suggestions', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['writer_job_id'], ['writer_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writer_drafts_id'), 'writer_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_writer_drafts_writer_job_id'), 'writer_drafts', ['writer_job_id'], unique=False)
    
    # Storage and Usage tables
    op.create_table('storage_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_uuid', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('file_uuid')
    )
    op.create_index(op.f('ix_storage_files_file_uuid'), 'storage_files', ['file_uuid'], unique=True)
    op.create_index(op.f('ix_storage_files_id'), 'storage_files', ['id'], unique=False)
    op.create_index(op.f('ix_storage_files_organization_id'), 'storage_files', ['organization_id'], unique=False)
    
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=False)
    op.create_index(op.f('ix_usage_events_organization_id'), 'usage_events', ['organization_id'], unique=False)
    op.create_index('idx_usage_org_month', 'usage_events', ['organization_id', 'created_at'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_org_month', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_organization_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_storage_files_organization_id'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_id'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_file_uuid'), table_name='storage_files')
    op.drop_table('storage_files')
    op.drop_index(op.f('ix_writer_drafts_writer_job_id'), table_name='writer_drafts')
    op.drop_index(op.f('ix_writer_drafts_id'), table_name='writer_drafts')
    op.drop_table('writer_drafts')
    op.drop_index(op.f('ix_writer_jobs_user_id'), table_name='writer_jobs')
    op.drop_index(op.f('ix_writer_jobs_project_id'), table_name='writer_jobs')
    op.drop_index(op.f('ix_writer_jobs_organization_id'), table_name='writer_jobs')
    op.drop_index(op.f('ix_writer_jobs_job_uuid'), table_name='writer_jobs')
    op.drop_index(op.f('ix_writer_jobs_id'), table_name='writer_jobs')
    op.drop_table('writer_jobs')
    op.drop_index(op.f('ix_report_exports_report_id'), table_name='report_exports')
    op.drop_index(op.f('ix_report_exports_id'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_uuid'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_organization_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_webhooks_webhook_uuid'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_organization_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_batch_job_items_id'), table_name='batch_job_items')
    op.drop_index(op.f('ix_batch_job_items_batch_job_id'), table_name='batch_job_items')
    op.drop_table('batch_job_items')
    op.drop_index(op.f('ix_batch_jobs_user_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_project_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_organization_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_batch_uuid'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
